import type { Agent, Property, Testimonial } from "./types";
import { PlaceHolderImages } from "./placeholder-images";

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const agents: Agent[] = [
  {
    id: "agent-1",
    name: "Jane Doe",
    title: "Senior Real Estate Agent",
    phone: "123-456-7890",
    email: "jane.doe@rahmanestates.com",
    bio: "With over 15 years of experience in the luxury real estate market, Jane has a proven track record of success. Her deep understanding of the market and commitment to her clients make her a trusted advisor.",
    image: getImage("agent-1"),
  },
  {
    id: "agent-2",
    name: "John Smith",
    title: "Commercial Property Specialist",
    phone: "098-765-4321",
    email: "john.smith@rahmanestates.com",
    bio: "John specializes in commercial properties, from office spaces to retail locations. His sharp negotiation skills and extensive network ensure the best deals for his clients.",
    image: getImage("agent-2"),
  },
    {
    id: "agent-3",
    name: "Emily White",
    title: "Residential Agent",
    phone: "555-123-4567",
    email: "emily.white@rahmanestates.com",
    bio: "Emily is passionate about helping families find their dream homes. Her friendly approach and attention to detail make the home-buying process a breeze.",
    image: getImage("agent-3"),
  },
];

export const properties: Property[] = [
  {
    id: "prop-1",
    title: "Modern Beachfront Villa",
    price: 3500000,
    location: "Malibu, CA",
    address: "25000 Pacific Coast Hwy, Malibu, CA 90265",
    bedrooms: 5,
    bathrooms: 5.5,
    squareFootage: 4500,
    description: "Experience luxury living in this stunning modern villa with breathtaking ocean views. Features an open-plan living area, infinity pool, and direct beach access. Perfect for those who seek tranquility and elegance.",
    propertyType: "Villa",
    amenities: ["Infinity Pool", "Private Beach Access", "Home Theater", "Gourmet Kitchen", "2-Car Garage"],
    uniqueFeatures: "Floor-to-ceiling windows with panoramic ocean views.",
    images: [getImage("property-1-1"), getImage("property-1-2")],
    agentId: "agent-1",
    coordinates: { lat: 34.038, lng: -118.687 },
  },
  {
    id: "prop-2",
    title: "Cozy Suburban Family Home",
    price: 850000,
    location: "Austin, TX",
    address: "1234 Maple Street, Austin, TX 78704",
    bedrooms: 4,
    bathrooms: 3,
    squareFootage: 2800,
    description: "A beautiful and spacious family home in a quiet suburban neighborhood. Features a large backyard with a deck, a newly renovated kitchen, and a cozy fireplace. Close to top-rated schools and parks.",
    propertyType: "House",
    amenities: ["Large Backyard", "Deck", "Renovated Kitchen", "Fireplace", "2-Car Garage"],
    uniqueFeatures: "Custom-built treehouse in the backyard.",
    images: [getImage("property-2-1")],
    agentId: "agent-3",
    coordinates: { lat: 30.244, lng: -97.761 },
  },
  {
    id: "prop-3",
    title: "Chic Downtown Apartment",
    price: 1200000,
    location: "New York, NY",
    address: "50 W 15th St, New York, NY 10011",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1500,
    description: "Live in the heart of the city in this chic and modern apartment. With stunning city views, high-end finishes, and access to premium building amenities, it offers the ultimate urban living experience.",
    propertyType: "Apartment",
    amenities: ["24/7 Doorman", "Fitness Center", "Rooftop Terrace", "Concierge Service"],
    uniqueFeatures: "Balcony overlooking the city skyline.",
    images: [getImage("property-3-1")],
    agentId: "agent-1",
    coordinates: { lat: 40.737, lng: -73.996 },
  },
  {
    id: "prop-4",
    title: "Luxury High-Rise Condo",
    price: 2100000,
    location: "Miami, FL",
    address: "1100 Brickell Bay Dr, Miami, FL 33131",
    bedrooms: 3,
    bathrooms: 3.5,
    squareFootage: 2200,
    description: "A sophisticated condo in a luxury high-rise, offering resort-style living. Enjoy stunning bay views, a private elevator, and access to exclusive amenities including a spa and multiple pools.",
    propertyType: "Condo",
    amenities: ["Bay Views", "Private Elevator", "Spa", "Fitness Center", "Valet Parking"],
    uniqueFeatures: "Expansive terrace perfect for entertaining.",
    images: [getImage("property-4-1")],
    agentId: "agent-2",
    coordinates: { lat: 25.763, lng: -80.188 },
  },
  {
    id: "prop-5",
    title: "Spacious Garden House",
    price: 975000,
    location: "Portland, OR",
    address: "3000 SE Ankeny St, Portland, OR 97214",
    bedrooms: 5,
    bathrooms: 3,
    squareFootage: 3200,
    description: "Charming and spacious house with a beautiful, mature garden. This home blends classic architecture with modern updates. Features a large master suite, a sunroom, and a finished basement.",
    propertyType: "House",
    amenities: ["Mature Garden", "Sunroom", "Finished Basement", "Hardwood Floors"],
    uniqueFeatures: "A dedicated workshop space in the garage.",
    images: [getImage("property-5-1")],
    agentId: "agent-3",
    coordinates: { lat: 45.521, lng: -122.634 },
  },
  {
    id: "prop-6",
    title: "Eco-Friendly Apartment Complex",
    price: 650000,
    location: "Denver, CO",
    address: "2525 15th St, Denver, CO 80211",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1300,
    description: "Modern living in an eco-friendly building. This apartment features sustainable materials, energy-efficient appliances, and a community garden. Located in a vibrant neighborhood with easy access to bike trails.",
    propertyType: "Apartment",
    amenities: ["LEED Certified Building", "Community Garden", "Bike Storage", "Energy-Efficient Appliances"],
    uniqueFeatures: "Rooftop solar panels contribute to lower utility costs.",
    images: [getImage("property-6-1")],
    agentId: "agent-2",
    coordinates: { lat: 39.757, lng: -105.007 },
  },
];

export const testimonials: Testimonial[] = [
  {
    name: "Michael Scott",
    location: "Malibu, CA",
    quote: "Working with Rahman Estates was a dream. They found us the perfect home in less than a month. The process was seamless and professional.",
    image: getImage("testimonial-1"),
  },
  {
    name: "Sarah Johnson",
    location: "Austin, TX",
    quote: "As a first-time homebuyer, I was nervous, but my agent at Rahman Estates guided me through every step with patience and expertise. I couldn't be happier!",
    image: getImage("testimonial-2"),
  },
  {
    name: "David & Maria Chen",
    location: "New York, NY",
    quote: "They handled the sale of our property with incredible efficiency and got us a price that exceeded our expectations. Truly the best in the business.",
    image: getImage("testimonial-3"),
  },
  {
    name: "Hans & Gretel",
    location: "Miami, FL",
    quote: "Rahman Estates made our international move so much easier. Their knowledge of the Miami market is unparalleled.",
    image: getImage("testimonial-4"),
  },
  {
    name: "Peter Jones",
    location: "Denver, CO",
    quote: "Selling our home was a breeze with John. He was professional, efficient, and got us a fantastic price.",
    image: getImage("testimonial-5"),
  },
  {
    name: "Alex Ramirez",
    location: "Portland, OR",
    quote: "The best real estate company I've ever dealt with. Very professional, experienced and helpful agents and brokers.",
    image: getImage("testimonial-6"),
  },
  {
    name: "Jessica Liu",
    location: "Denver, CO",
    quote: "Our agent was fantastic! She was so patient and helpful, and she found us the perfect house. We couldn't be happier.",
    image: getImage("testimonial-7"),
  },
  {
    name: "Tom Wilson",
    location: "Seattle, WA",
    quote: "I highly recommend Rahman Estates. Their team is knowledgeable, and they made our home buying experience a positive one.",
    image: getImage("testimonial-8"),
  },
];
